apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-jenkins
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-jenkins
  template:
    metadata:
      labels:
        app: hello-jenkins
    spec:
      containers:
      - name: hello
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
